services:
  postgis:
    image: postgis/postgis:17-master
    container_name: postgis
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"           # cambiar a "5433:5432" si ya hay otro PostgreSQL
    volumes:
      - postgis_data:/var/lib/postgresql/data   # named volume manejado por Docker

  geoserver:
    image: docker.osgeo.org/geoserver:2.24.x
    container_name: geoserver
    restart: always
    depends_on:
      - postgis
    environment:
      TZ: America/Argentina/Cordoba
      INSTALL_EXTENSIONS: "true"
      STABLE_EXTENSIONS: "postgresql,ogr,monitor,importer,ysld"
      # COMMUNITY_EXTENSIONS: "cog,mbtiles"
    ports:
      - "8080:8080"           # acceso: http://localhost:8080/geoserver
    volumes:
      - ./geoserver_data:/opt/geoserver_data      # carpeta local visible desde su host
      - ./geoserver_logs:/var/log/geoserver       # logs accesibles localmente

  web:
    image: node:20-alpine
    container_name: ol-lab-web
    restart: always
    depends_on:
      - postgis
    working_dir: /app
    environment:
      PORT: 3000
      PGHOST: postgis         # nombre del servicio de PostGIS en esta red
      PGPORT: 5432            # puerto interno del contenedor PostGIS
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: geoserver
    volumes:
      - ./ol-lab:/app
    ports:
      - "3000:3000"          # acceso: http://localhost:3000/
    command: sh -c "npm install && npm run dev"

volumes:
  postgis_data:

